title: hmoats.github.io
description: Collection of projects, labs, notes, tips, docs, etc.
show_downloads: false
theme: jekyll-theme-modernisttitle: hmoats.github.io
google_analytics: [UA-150074282-1]
